[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
test2 = "F4JnCD9KASp74g2zCg8GkoSj1boKKzCcZvq9Fjs4LzBz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/hussain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
